### ISSUE TITLE
Refurnish the README.md file 

### ISSUE THREAD

**Issue by EmpAsh938** [EmpAsh938/write-in#15]
Keep it simple and dont overdo it.

**Comment by the-amazing-atharva** [comment]
Hi!

I would like to work on the README to make it more visually appealing by adding new objects and making subtle syntax changes
Could you assign me ??

**Comment by EmpAsh938** [comment]
Thanks for your consideration. Looking forward to your work

**Comment by the-amazing-atharva** [comment]
Thanks for the reply, working on it soon!

**Comment by the-amazing-atharva** [comment]
Hey @EmpAsh938 I am almost done

Could you attach a cropped logo of your site here in the comments

**Comment by EmpAsh938** [comment]
![android-chrome-192x192](https://user-images.githubusercontent.com/38640912/216804045-8464f5e9-3aa0-4ec4-8f44-b6d2b34edae9.png)
![android-chrome-512x512](https://user-images.githubusercontent.com/38640912/216804046-305a222c-1bfd-4b74-bce1-834edc415bc6.png)
All are used for favicons. Tell me if you need any support

**Comment by the-amazing-atharva** [comment]
Thanks for posting,

Will update the README soon

**Comment by EmpAsh938** [comment]
cant wait for the result
